/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class Calculator_Main_screen extends javax.swing.JFrame implements ActionListener {
      String s0="",s1="",s2="";
    /**
     * Creates new form Calculator_Main_screen
     */
    public Calculator_Main_screen() {
         try{
            ImageIcon image=new ImageIcon(getClass().getResource("/Icons/mainicon.png"));
            setIconImage(image.getImage());
        }catch(Exception ex){
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtndiv = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtnmul = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtndecimal = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnsub = new javax.swing.JButton();
        jbtnequal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCalculations = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculator World!!!");

        jbtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(this);

        jbtn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(this);

        jbtndiv.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtndiv.setText("%");
        jbtndiv.addActionListener(this);

        jbtn3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(this);

        jbtn4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(this);

        jbtn5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(this);

        jbtnmul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnmul.setText("*");
        jbtnmul.addActionListener(this);

        jbtn6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(this);

        jbtn7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(this);

        jbtn8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(this);

        jbtnadd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnadd.setText("+");
        jbtnadd.addActionListener(this);

        jbtn9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(this);

        jbtndecimal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtndecimal.setText(".");
        jbtndecimal.addActionListener(this);

        jbtn0.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(this);

        jbtnsub.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnsub.setText("-");
        jbtnsub.addActionListener(this);

        jbtnequal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnequal.setText("=");
        jbtnequal.addActionListener(this);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_Closed_Book_Icon_1741323.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_diploma_icon_1741321 (1).png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_paper_with_A_text_1741316.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_teacher_writing_on_board_1741313.png"))); // NOI18N

        jtfCalculations.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconfinder_white_board_with_text_icon_1741312.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(jtfCalculations, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtndecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jtfCalculations, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jbtn1) {
            Calculator_Main_screen.this.jbtn1ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn2) {
            Calculator_Main_screen.this.jbtn2ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn3) {
            Calculator_Main_screen.this.jbtn3ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn4) {
            Calculator_Main_screen.this.jbtn4ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn5) {
            Calculator_Main_screen.this.jbtn5ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn6) {
            Calculator_Main_screen.this.jbtn6ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn7) {
            Calculator_Main_screen.this.jbtn7ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn8) {
            Calculator_Main_screen.this.jbtn8ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn9) {
            Calculator_Main_screen.this.jbtn9ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtn0) {
            Calculator_Main_screen.this.jbtn0ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtndecimal) {
            Calculator_Main_screen.this.jbtndecimalActionPerformed(evt);
        }
        else if (evt.getSource() == jbtndiv) {
            Calculator_Main_screen.this.jbtndivActionPerformed(evt);
        }
        else if (evt.getSource() == jbtnmul) {
            Calculator_Main_screen.this.jbtnmulActionPerformed(evt);
        }
        else if (evt.getSource() == jbtnadd) {
            Calculator_Main_screen.this.jbtnaddActionPerformed(evt);
        }
        else if (evt.getSource() == jbtnsub) {
            Calculator_Main_screen.this.jbtnsubActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1) {
            Calculator_Main_screen.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jbtnequal) {
            Calculator_Main_screen.this.jbtnequalActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents
   
    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String One= String.valueOf("1");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+One);
       }else{
        jtfCalculations.setText(One);
       }
       if(!s1.equals("")){
           s2=s2+One;
           jtfCalculations.setText(s0+s1+s2);
       }else{
           jtfCalculations.setText(s+One);
       }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
       String Two= String.valueOf("2");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }
        if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
         String Two= String.valueOf("3");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }
       if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
         String Two= String.valueOf("4");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }
       if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
 String Two= String.valueOf("5");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
 String Two= String.valueOf("6");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
 String Two= String.valueOf("7");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
 String Two= String.valueOf("8");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
 String Two= String.valueOf("9");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
       String Two= String.valueOf("0");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtndecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndecimalActionPerformed
       String Two= String.valueOf(".");
        String s= jtfCalculations.getText();
       if(!s.isEmpty()){
       jtfCalculations.setText(s+Two);
       }else{
        jtfCalculations.setText(Two);
       }if(s1.equals("+") || s1.equals("%")||s1.equals("*")||s1.equals("-")){
           s2=s2+"0"+Two;
           jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jbtndecimalActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
       s0 = jtfCalculations.getText();
       s1 = String.valueOf("%");
      jtfCalculations.setText(s0+s1);
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmulActionPerformed
          s0 = jtfCalculations.getText();
       s1 = String.valueOf("*");
      jtfCalculations.setText(s0+s1);
    }//GEN-LAST:event_jbtnmulActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
          s0 = jtfCalculations.getText();
       s1 = String.valueOf("+");
      jtfCalculations.setText(s0+s1);
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubActionPerformed
         s0 = jtfCalculations.getText();
       s1 = String.valueOf("-");
      jtfCalculations.setText(s0+s1);
    }//GEN-LAST:event_jbtnsubActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String s= jtfCalculations.getText();
       if(!s.isEmpty()){
           s0=s1=s2="";
          jtfCalculations.setText(s0+s1+s2);
       }
    }//GEN-LAST:event_jButton1ActionPerformed
Double Final_answer;
    private void jbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalActionPerformed
      if(s1.equals("%")){
          Final_answer = Double.parseDouble(s0)/Double.parseDouble(s2);
          jtfCalculations.setText(s0+s1+s2+" = "+String.valueOf(Final_answer));
      }else if(s1.equals("*")){
          Final_answer = Double.parseDouble(s0)*Double.parseDouble(s2);
          jtfCalculations.setText(s0+s1+s2+" = "+String.valueOf(Final_answer));
      }else if(s1.equals("+")){
          Final_answer = Double.parseDouble(s0)+ Double.parseDouble(s2);
          jtfCalculations.setText(s0+s1+s2+" = "+String.valueOf(Final_answer));
      }else if(s1.equals("-")){
          Final_answer = Double.parseDouble(s0)- Double.parseDouble(s2);
          jtfCalculations.setText(s0+s1+s2+" = "+String.valueOf(Final_answer));
      }
    }//GEN-LAST:event_jbtnequalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator_Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator_Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator_Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator_Main_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator_Main_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtndecimal;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnmul;
    private javax.swing.JButton jbtnsub;
    private javax.swing.JTextField jtfCalculations;
    // End of variables declaration//GEN-END:variables
}
